# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4a84f04647e003c1526b7597962ba01b513ec51c7377a272a2ddaa4bbe83fbfe97555756f49562f5d8656f37259fc3af705fc6fabf7f9f36981f5eae0893c31

test:
  secret_key_base: b00987619828dbd8777f349bdb32fa9fbb8b4e80947a6e98d8c983d71824daa0a97e7c9099428919a4ed26d4a8c046abb6545f3e30bf7dedf4df1f4bf18be702

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
